### PR TITLE
Simple autocompletion for the REPL (fixes #59)

### LINKED ISSUE #59: autocompletion in Skewer REPL
So I was able to get autocompletion working with tern-mode and company-tern in Javascript buffers, but this does not work in the Skewer REPL.  Any idea why this might be?

### PR DESCRIPTION
**Pull request by TatriX**

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks for giving this a shot. There are two minor things still needed: `(require 'company)` and adding `company` (0.9.2?) as a new dependency in skewer-mode-pkg.el.

But more importantly, how do I use this? I've never used `company-mode` before. I fired up the REPL, enabled company-mode, and can't really get it to do anything. I can tell roughly what it's doing — figuring out the name of the object to query and fetching its properties — but I don't know how that connects to company-mode.

**Comment by TatriX** [comment]
Usually company mode will run a completion after a short delay if there are more then `company-minimum-prefix-length` characters in the prefix.

```
(add-hook 'after-init-hook 'global-company-mode)
(global-set-key (kbd "C-M-i") 'company-complete)
```
2017-01-21-202516_384x451_scrot

**Comment by TatriX** [comment]
I believe users don't need company mode to use the skewer-mode.
When buffer enters the `skewer-repl-mode` it just sets local variable:
```
(setq-local company-backends '(company-skewer-repl))
```
So if user has company mode installed it completion should work out of the box. If no company mode available nothing happens.

**Comment by skeeto** [comment]
Opportunistic use of company-mode is perfect! I've merged with additional changes.

* I wrapped the three places it touches company-mode with `with-no-warning` to keep the compiler quiet. All three are perfectly safe without company-mode being loaded.

* I moved the JavaScript out into skewer.js. It's now a formal Skewer "method" called `completions`. The string-building hack is no longer necessary and accessing completions is a lot simpler:

~~~el
(skewer-eval-synchronously "document.location"
                           :type "completions"
                           :extra '((regexp . "^h")))

;; => ((value . ["href" "host" "hostname" "hash"])
;;     (status . "success")
;;     (type . "completions")
;;     (id . "24219a5f06cbc5c"))
~~~

* `skewer-repl--get-completion-expression` returns nil instead of `window`. This is because an `arg` of of `"window"` is fundamentally different than an `arg` that needs to consult `window`, and they must be handled differently. Without this there's also the funky issue where an `arg` of `"document"` returned `"window"` and then `pattern` ends up as `"t"` because the substring goes off the length of `"window"`. This fixes top-level completions.

**Comment by TatriX** [comment]
Awesome, thank you!

**Pull request merged**
